### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by androidcn** [codepongo/StockCalculator#1]
记录Bug
- 001979 这个股票 显示 1979
- 图标显示为"元"
- 无法获取股票的名称

"计算"板块应该改为"买入""卖出"作为记录-用"损益计算""保本价格"来做记录我觉得不太好.

![img_1436](https://cloud.githubusercontent.com/assets/271715/13325742/17156aa0-dc1e-11e5-9942-1434b1412c6e.PNG)
![img_1435](https://cloud.githubusercontent.com/assets/271715/13325744/171691a0-dc1e-11e5-9dae-d955b558df19.PNG)
![img_1434](https://cloud.githubusercontent.com/assets/271715/13325743/171640e2-dc1e-11e5-8f64-dbcd17630b43.PNG)

**Comment by codepongo** [comment]
fix:001979 这个股票 显示 1979
improvement:图标显示为"元"
reject:无法获取股票的名称
improvement:"计算"板块应该改为"买入""卖出"作为记录-用"损益计算""保本价格"来做记录我觉得不太好.
